Export Phyx view as CSV
phyloref/klados pull request #238
Opened 2022-02-16 05:57 UTC by gaurav

This PR adds an "Export as CSV" button to the Phyloref summary in the Phyx view so that that table can be exported as a CSV file.

Closes #225.

WIP Should probably test this a bit more before review.

2022-04-08 19:37 UTC, hlapp reviewed
Nothing that looks obviously questionable here, but I don't see a screenshot of how this would appear, and I don't see an example csv that this would produce. So kind of hard to confidently give 👍🏻.

2022-04-27 01:31 UTC, gaurav commented
> Nothing that looks obviously questionable here, but I don't see a screenshot of how this would appear, and I don't see an example csv that this would produce. So kind of hard to confidently give 👍🏻.

Good catch! I've updated the PR description with a screenshot and a link to two example CSVs.

2022-04-27 15:18 UTC, hlapp requested changes
UI appearance looks fine. As for the CSV, my one gripe with it is that the first column pretends that phyloreferences are identified by label, which of course they aren't. My suggestion would be to have two columns for Phyloreference ID and label, respectively, or if only one column at the very least be clear in the column label that the value is a label.

2022-06-15 04:11 UTC, gaurav commented
Fixed in d3f7582277f9. The file now includes a "Phyloreference ID" field -- if an `@id` is set, it will be used; otherwise, each phyloreference is referred to as `#phyloref0`, `#phyloref1`, and so on. See example CSV output in [Alligatoridae_Alligatorinae_and_4_others.csv](https://github.com/phyloref/klados/files/8905597/Alligatoridae_Alligatorinae_and_4_others.csv).

2022-06-15 16:26 UTC, hlapp approved these changes
Looks good with the ID present now.

Two remaining quibbles:
1. We're not including the type of specifier, so are leaving it up to the reader of the CSV to either assume it's a taxon name, or to apply some guessing logic. However, we do know the type, don't we? Same for expected and actual. Or maybe all we're saying is that these are node labels?
2. It seems that the number of internal and external specifier columns is not fixed, but dynamic depending on however many the phyloreference with the most such specifiers happens to use. I suppose that's unavoidable when flattening out to CSV. But wouldn't it be better to have the columns whose number is dynamic appear last in the column order, rather than in the middle?

I think both of these are minor quibbles, and rather than holding up this PR should probably rather be turned into issues, which is why I'm approving.

2022-08-21 04:40 UTC, gaurav commented
> We're not including the type of specifier, so are leaving it up to the reader of the CSV to either assume it's a taxon name, or to apply some guessing logic. However, we do know the type, don't we? Same for expected and actual. Or maybe all we're saying is that these are node labels?

Ah, good catch! That's a bug on my part -- I wrote `TaxonConceptWrapper` instead of `TaxonomicUnitWrapper`, which has the logic for displaying specimens (with the phrase `Specimen [occurrence ID]`) or an external reference (in the format `<url>`). Fixed in 41dd4cc. I can't really test this since our only current test file only uses taxon names, but I've made a note on #232 to check the CSV export once we have more complicated phyloreferences in here.

> It seems that the number of internal and external specifier columns is not fixed, but dynamic depending on however many the phyloreference with the most such specifiers happens to use. I suppose that's unavoidable when flattening out to CSV. But wouldn't it be better to have the columns whose number is dynamic appear last in the column order, rather than in the middle?

In theory, the phylogeny columns are also dynamic, as you are allowed to have multiple phylogenies in a single Phyx file. If there were multiple phylogenies in [Alligatoridae_Alligatorinae_and_4_others.csv](https://github.com/phyloref/klados/files/8905597/Alligatoridae_Alligatorinae_and_4_others.csv), each would be listed after all the other columns with the columns `[phylogeny label] expected` and `[phylogeny label] actual`. So even if I were to move them to before the specifier columns, they would still require some processing to be interpreted correctly.

I'll go ahead and merge this PR, but please do open an issues if you think we should output the phylogeny resolutions in CSV in another format.

2022-08-21 04:40 UTC, merged

2022-08-21 20:03 UTC, hlapp commented
> In theory, the phylogeny columns are also dynamic, as you are allowed to have multiple phylogenies in a single Phyx file.

Good point. So I think the main thing left is to document the CSV format, either in plain text, or for example in LinkML, so that downstream consumers know what to expect? Should that become an issue in the tracker so we don't forget?

2022-08-22 03:18 UTC, gaurav commented
> Good point. So I think the main thing left is to document the CSV format, either in plain text, or for example in LinkML, so that downstream consumers know what to expect? Should that become an issue in the tracker so we don't forget?

Sounds good! I'm not sure if LinkML supports dynamic column names in this way, but we should definitely document this somewhere. Filed as #257.